// performance-react/src/App.js
import './App.css';
import React, { useState, useEffect } from 'react';
import RenderNumber from './RenderNumber/RenderNumber';
import TableCel from './TableCel/TableCel';
import { getData } from './services/data.service';

function App() {
  const addCount = (value) => {
    let number = count;
    for (let i = 0; i < value; i++) {
      number += 1;
      setNumber(number);
    }
  };

  useEffect(() => {
    getData().then((response) => {
      response.forEach((item) => {
        item.disabled = false;
      });
      setData(response.slice(0, 1000));
    });
  }, []);

  const toogleList = () => {
    setShow(!show);
  };

  const disableCountry = (country) => {
    setData(
      data.map((item) => {
        if (item.country === country) {
          item.disabled = !item.disabled;
        }
        return item;
      }),
    );
  };

  const [count, setNumber] = useState(0);
  const [show, setShow] = useState(false);
  const [data, setData] = useState([]);

  const getTable = () => {
    if (!show) {
      return null;
    }
    const table = () => {
      return data.map((item, index) => {
        return (
          <TableCel item={item} disableCountry={disableCountry}></TableCel>
        );
      });
    };
    return (
      <div className="main-table">
        <div className="row table-header">
          <div className="col">Year</div>
          <div className="col">Quarter</div>
          <div className="col">Month</div>
          <div className="col">Term</div>
          <div className="col">Country</div>
          <div className="col">Total</div>
          <div className="col">Action</div>
        </div>
        {table()}
      </div>
    );
  };

  return (
    <div className="App">
      <RenderNumber number={count}></RenderNumber>
      <button onClick={() => addCount(1)}>Add 1</button>
      <button onClick={() => addCount(10)}>Add 10</button>
      <p>----</p>
      <div>Quantity: {data.length}</div>
      <button onClick={toogleList}>{show ? 'Hide' : 'Show'}</button>
      {getTable()}
    </div>
  );
}

export default App;

// performance-vue/src/App.vue
<template>
<div>
  <RenderNumber v-bind:number="number" />
  <button @click="addCount(1)">add 1</button>
  <button @click="addCount(10)">add 10</button>

  <p>----</p>
  <div>Quantity: {{data.length}}</div>
  <button @click="toogleList">{{show ? 'Hide' : 'Show'}}</button>

  <div class="main-table" v-if="show">
    <div class="row table-header">
      <div class="col">Year</div>
      <div class="col">Quarter</div>
      <div class="col">Month</div>
      <div class="col">Term</div>
      <div class="col">Country</div>
      <div class="col">Total</div>
      <div class="col">Action</div>
    </div>
    <TableCel v-for="(item, idx) in data" :key="idx" v-bind:item="item" v-bind:disableCountry="disableCountry" />
  </div>
</div>
</template>

<script>
import RenderNumber from './components/RenderNumber.vue'
import TableCel from './components/TableCel';
import { getData } from './services/data.service';

export default {
  name: 'App',
  components: {
    RenderNumber,
    TableCel
  },
  created: function () {
    getData().then((response) => {
      response.forEach((item) => {
        item.disabled = false;
      });
      this.data = response.slice(0, 1000);
    });
  },
  data() {
    return {
      number: 0,
      data: [],
      show: false,
    }
  },
  methods: {
    addCount(quant) {
      for (let i = 0; i < quant; i++) {
        this.number += 1;
      }
    },
    toogleList() {
      this.show = !this.show;
    },
    disableCountry(country) {
      this.data = this.data.map((item) => {
        if (item.country === country) {
          item.disabled = !item.disabled;
        }
        return item;
      });
    }

  },
}
</script>

<style>
#app {
  text-align: center;
}
</style>
